name: hospitalityapp
description: A new Flutter project.
publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  nice_button: ^0.1.7
  spinner: ^1.0.1
  spinner_input: ^0.1.2
  datetime_picker_formfield: ^0.4.3
  flutter_native_timezone: ^1.0.2
  carousel_slider: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true


  assets:
    - assets/imagebg.jpg
    - assets/

